-- Migration 001: Add has_ipset column to peers table
--
-- STATUS: This migration is handled programmatically.
-- The addColumnIfMissing("peers", "has_ipset") call in migrations.go
-- (inside migrateSchema) automatically adds the has_ipset column if it
-- does not already exist. This SQL file is kept as documentation only;
-- the actual migration logic lives in the Go code.
--
-- Date: 2026-03-30
-- Purpose: Enable ipset capability detection for group-based firewall rules
